### ISSUE TITLE
ImportError: cannot import name 'forest' from 'river'

### ISSUE THREAD

**Issue by tnalyahya** [online-ml/river#1359]
Hi,

I'm interested in forest incremental learning, but facing an issue with importing forest.
`from river import forest`
`
Traceback (most recent call last):
  File "/mainfs/scratch/tna1a19/oml_river/river_defult.py", line 7, in <module>
    from river import forest
ImportError: cannot import name 'forest' from 'river' (/home/tna1a19/.conda/envs/myenv/lib/python3.11/site-packages/river/__init__.py)
`
Any suggestion?

**Comment by smastelini** [comment]
Hi @tnalyahya. Which river version are you using?

**Comment by tnalyahya** [comment]
I installed it using Conda [()](https://anaconda.org/conda-forge/river) 
`conda install -c conda-forge river`
so, it is 0.13.0

**Comment by smastelini** [comment]
You should try pip instead. The forest module was introduce in the newer versions. If you do `pip install river`, you will get the latest version :D

**Comment by tnalyahya** [comment]
thanks!
I installed it using pip, but had another issue with the library!

`from river import evaluate
from river import forest
from river import metrics
from river.datasets import synth

dataset = synth.ConceptDriftStream(
    seed=42,
    position=500,
    width=40
).take(1000)

model = forest.ARFClassifier(seed=8, leaf_prediction="mc")

metric = metrics.Accuracy()

print(evaluate.progressive_val_score(dataset, model, metric))`


`  File "/mainfs/scratch/tna1a19/oml_river/river_defult.py", line 2, in <module>
    from river import forest
  File "/home/tna1a19/.local/lib/python3.9/site-packages/river/forest/__init__.py", line 4, in <module>
    from .adaptive_random_forest import ARFClassifier, ARFRegressor
  File "/home/tna1a19/.local/lib/python3.9/site-packages/river/forest/adaptive_random_forest.py", line 14, in <module>
    from river.tree.hoeffding_tree_classifier import HoeffdingTreeClassifier
  File "/home/tna1a19/.local/lib/python3.9/site-packages/river/tree/__init__.py", line 54, in <module>
    from . import base, splitter
  File "/home/tna1a19/.local/lib/python3.9/site-packages/river/tree/splitter/__init__.py", line 21, in <module>
    from .gaussian_splitter import GaussianSplitter
  File "/home/tna1a19/.local/lib/python3.9/site-packages/river/tree/splitter/gaussian_splitter.py", line 6, in <module>
    from river.proba import Gaussian
  File "/home/tna1a19/.local/lib/python3.9/site-packages/river/proba/__init__.py", line 6, in <module>
    from .gaussian import Gaussian, MultivariateGaussian
  File "/home/tna1a19/.local/lib/python3.9/site-packages/river/proba/gaussian.py", line 7, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
`

**Comment by MaxHalford** [comment]
Yes that's a known issue. You need to install `pytest` (run `pip install pytest`)

That issue will be fixed with version 0.20.
