### ISSUE TITLE
Having error in  import river

### ISSUE THREAD

**Issue by caiyuan11** [online-ml/river#862]
hello! I am a beginner of online learning. 
An unexpected error occurred when I tried to import module
 like the code : `from river.drift import EDDM`
I wonder if anyone has encountered the same question, could you help me solve it?

detail as follow:
Traceback (most recent call last):
  File "/data3/caiyuan/code/test.py", line 1, in <module>
    from river.drift import EDDM
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/river/__init__.py", line 9, in <module>
    from . import (
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/river/anomaly/__init__.py", line 13, in <module>
    from .hst import HalfSpaceTrees
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/river/anomaly/hst.py", line 7, in <module>
    from river.tree.base import Branch, Leaf
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/river/tree/__init__.py", line 55, in <module>
    from .hoeffding_adaptive_tree_classifier import HoeffdingAdaptiveTreeClassifier
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/river/tree/hoeffding_adaptive_tree_classifier.py", line 7, in <module>
    from .nodes.hatc_nodes import (
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/river/tree/nodes/hatc_nodes.py", line 5, in <module>
    from river.drift import ADWIN
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/river/drift/__init__.py", line 10, in <module>
    from .adwin import ADWIN
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/river/drift/adwin.py", line 3, in <module>
    from .adwin_c import AdaptiveWindowing
  File "build/lib.linux-x86_64-3.7/river/drift/adwin_c.pyx", line 1, in init river.drift.adwin_c
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject

**Comment by MaxHalford** [comment]
Hello! Can you try upgrading numpy? Sometimes this happens, though I'm not sure why. I thought we solved this problem.

**Comment by hoanganhngo610** [comment]
Since this issue is fully resolved, I will close this by now!
